### ISSUE TITLE
"listenForReplays" hangs browser when using hash history without query key

### ISSUE THREAD

**Issue by mezzario** [reactjs/react-router-redux#279]
If using custom hash history without query key (example from `react-router`):

```js
// v2.0.0
import { Router, useRouterHistory } from 'react-router'
import { createHashHistory } from 'history'
// useRouterHistory creates a composable higher-order function
const appHistory = useRouterHistory(createHashHistory)({ queryKey: false })
<Router history={appHistory}/>
```

Then `listenForReplays` will infinitely replace location on first dispatched action (because `key` always `null`):

```js
// If we're resetting to the beginning, use the saved initial value. We
// need to dispatch a new action at this point to populate the store
// appropriately.
if (location.key === initialLocation.key) {
  history.replace(initialLocation)
  return
}
```
https://github.com/reactjs/react-router-redux/blob/master/src/index.js#L83-L89

I suggest revising all code where `location.key` is used while keeping in mind that it can be `null`.

**Comment by mezzario** [comment]
@timdorr, is guess this is for you :)

**Comment by timdorr** [comment]
Hmm, this is just something not supported on 3.0. We use the key as an id for the location, rather than the location itself to determine if it has been reset or reloaded. No real way around that, since we would need to do a `deepEquals` check and I don't think we want to get into that right now.

I would check out the 4.0.0 beta and see if that works for you. It doesn't use the key, so it should work A-OK. It's coming relatively soon (just gotta test server side stuff), so it will be how things operate eventually anyways.
