### ISSUE TITLE
Redirect loop in IE9

### ISSUE THREAD

**Issue by lfrodrigues** [reactjs/react-router-redux#285]
I moved from redux-router to react-router-redux, all works find except I get a nasty infinite reload loop in IE9. The page just continually reloads (similar to what was reported here: https://github.com/acdlite/redux-router/issues/125)

As suggested in redux-router repository if I use hashHistory all works fine but with browserHistory it  doesn't. Is there a better way solve the problem without having to choose history depending on browser?

**Comment by timdorr** [comment]
IE9 doesn't support `pushState`, which is what `browserHistory` uses. If you need to support older versions of IE, then you have to either use `hashHistory` exclusively or switch out things based on browser sniffing.

**Comment by bob76828** [comment]
In my universal app, I use react-router-redux 4.0.0 and set the adjustUrlOnReplay option to false at syncHistoryWithStore method. It will be fixed redirect loop at IE9, but it has always used server-side rendering when you change the location.

**Comment by landabaso** [comment]
Sorry to pop up this issue again.

How do you safely determine whether a Browser **"supports"** pushHistory or not?
I'm having an issue with Android 4.0.4 Stock Browser (using react-router with react-router-redux).

There's also an infinite loop (as with IE9) but window.history & window.history.pushState are defined.
Thus, I cannot use a (!window.history) conditional check.

I guess the problem comes from a buggy implementation but cannot be sure.

Any ideas? Thanks!

**Comment by landabaso** [comment]
I'll reply to myself in case it helps others in the future:

There's a "supportsHistory" function used within react-router. It takes care of Android 4.0.* stuff (and other). See:

```
/**
 * Returns true if the HTML5 history API is supported. Taken from Modernizr.
 *
 * https://github.com/Modernizr/Modernizr/blob/master/LICENSE
 * https://github.com/Modernizr/Modernizr/blob/master/feature-detects/history.js
 * changed to avoid false negatives for Windows Phones: https://github.com/rackt/react-router/issues/586
 */

function supportsHistory() {
  var ua = navigator.userAgent;
  if ((ua.indexOf('Android 2.') !== -1 || ua.indexOf('Android 4.0') !== -1) && ua.indexOf('Mobile Safari') !== -1 && ua.indexOf('Chrome') === -1 && ua.indexOf('Windows Phone') === -1) {
    return false;
  }
  return window.history && 'pushState' in window.history;
}

```

It belongs to the "history" npm package.

The problem is it is not exported in any package (that I am aware).

Right now I'm importing it using this ugly piece of code:

`import { supportsHistory } from '../../../node_modules/react-router/node_modules/history/lib/DOMUtils'
`
(note the relative path "../../../" at the beginning may vary in your project)

**Comment by timdorr** [comment]
You can add history as a dependency and `import { supportsHistory } from 'history/lib/DOMUtils' `

**Comment by landabaso** [comment]
Thank you Tim! It works and it's more elegant.

**Comment by boyney123** [comment]
Been looking at this, just to let you all know history has changed the location of DOMUtils, so you will want to try this.

import { supportsHistory } from 'history/DOMUtils'
