### ISSUE TITLE
Include the router data in action payload

### ISSUE THREAD

**Issue by QuietOmen** [reactjs/react-router-redux#287]
I think it would be beneficial to include the router data in the payload of the action ```UPDATE_LOCATION``` so it can be used in the reducer. Currently I have to use the connect function and do this for each smart component. Location just doesn't have all the information that I need in order to change my redux state tree like I want to do. Basically I'm trying to determine the route that I'm currently on using the routes and the end route's name. I'm aware of there being activeStyle and IndexLink for assigning css to links for the active route, but I need to know what route is active in order to change the functionality and look of a common component depending on the current route. The component is a search bar and it should alter its size and layout depending on the page. The change is minor enough (basically css changes) that I don't want to make a completely separate component for the various pages. Maybe there's a better way to be doing this?

**Comment by timdorr** [comment]
The data you're trying to access is internal Router state. We don't want to run that through Redux because it doesn't behave the way that Redux likes to handle state. Trying to resolve that would result in a lot of problems and edge case behaviors.

I would instead hook this into a componentWillMount lifecycle where it can dispatch an action to indicate the current search bar layout. You don't have to maintain some sort of mapping that way. A component can simply ask it to get out of the way or say it's got room to grow.
