### ISSUE TITLE
How does SyncWithHystory knows store has changes as you dispatch history API like 'push' from react-router-redux

### ISSUE THREAD

**Issue by quarryman** [reactjs/react-router-redux#353]
Trying to understand basic usage of history API provided by this module.

Next code is assumed to change route

```
import { routerMiddleware, push } from 'react-router-redux'
store.dispatch(push('/any_route'))
```

'push' returns action of @@router/CALL_HISTORY_METHOD type.

_routerMiddleware_ is designed to tell exactly this action type from others and in case of dispatching 'push' it implicitly calls history.push which is clear. 

Browser location is changed and app should be notified of it.

In order to notify app 'syncHistoryWithStore' is used. Internally, 
`history.listen(handleLocationChange)` is called which actually listen to store changes using `store.subscribe()` and in case of location change in store dispatches LOCATION_CHANGED action

Here comes my question.
As our initially dispatched 'push' action is handled by middleware only and only calles history.push, (no reducer handles @@router/CALL_HISTORY_METHOD action except for middleware ) how does store.subscribe handler is called and who changes the store with new location as we just call history. push method?

**Comment by timdorr** [comment]
The middleware/actions and `syncHistoryWithStore` are really two independent tools provided by this library. You can use one without the other. They don't interact directly at all.

I'd suggest reading through [the `syncHistoryWithStore` code](https://github.com/reactjs/react-router-redux/blob/master/src/sync.js) in more detail. The basic gist is that we hook into `history.listen` to dispatch location changes to the store, and override the returned `listen` method to listen to store changes instead of history changes. We basically shim in the store in the middle of history's location change events.

**Comment by quarryman** [comment]
@timdorr hello.
Do I understand it right that
`unsubscribeFromHistory = history.listen(handleLocationChange)`
listens to history change and dispatches 'LOCATION_CHANGE' on history change and then you override
listen method to listen to store instead of history?
