### ISSUE TITLE
dispatch(push(...)) raises two redux actions

### ISSUE THREAD

**Issue by Strato** [reactjs/react-router-redux#417]
Hello,

When I dispatch the react-router-redux push action factory, I see in redux debug panel two actions being raised, both with the same location. The only difference is the "action" property in the payload is "push" the first time, and "pop" the second time. It makes the component associated with location render twice, which is annoying.

Are those two actions to be expected? Or is it a bug? Or am I possibly doing something wrong?

The router middleware is here. I'm just doing this:
```
const mapDispatchToProps = (dispatch, ownProps) => {
    return {
        push: (location: HistoryModule.LocationDescriptorObject) => {
            dispatch(push(location as any));
        }
    };
};
```
It's not called twice (I checked).

**Comment by Strato** [comment]
OK found it.

I tried to not dispatch/push from react-router-redux, just the withRoute decorator, and I could see it was not related.

My problem was I was missing a / in the pathname of the new location.
```
this.props.push({
    pathname: '/pack-management',
    query: { foobar: 'redacted' }
});
```
The missing / was automagically fixed, but it was also raising a hashLocationChanged event which in turn pushed a new history state.

**Comment by nickfujita** [comment]
+1 on this, thanks for documenting.

Also note that another side effect I was seeing of not prefixing pushes with '/' is that pushes start taking on to the end of the current url instead of replacing (see example below), and this messed up the routing when applying goBack().

route: /
component: index

action: push('aaa')
route: /aaa
component: aaa

action: push('bbb')
route: /aaa/bbb
component: bbb

action: push('ccc')
route: /aaa/bbb/ccc
component: ccc

action: goBack()
route: /aaa/bbb
component: ccc

No error message was given, but the component to route mapping was corrupted.

**Comment by fes300** [comment]
thank you very much for documenting, I spent waaay too much time on this :)

**Comment by shanSyapse** [comment]
This fixes the issue that I've been debugging for two days. Thanks
In our index route, we replaced the url with a path without the '/', and the component was rendered twice, together with two location change actions
Previous code:
```
  indexRoute: {
    onEnter: (nextState, replace) => replace('url_without_slash')
  },
```
Adding the '/' to the url fix it.
Fixed Code:
```
  indexRoute: {
    onEnter: (nextState, replace) => replace('/url_without_slash')
  },
```
Many thanks!
