### ISSUE TITLE
history v3.0 breaks react-router with invariant warning

### ISSUE THREAD

**Issue by leetercola** [reactjs/react-router-redux#436]
https://github.com/reactjs/react-router/pull/3571

**Comment by timdorr** [comment]
This library doesn't support history v3 yet.

**Comment by larrydahooster** [comment]
Hey, react router 3 was just released: https://github.com/ReactTraining/react-router/releases/tag/v3.0.0 and it is using history v3.0. Are there any plans on supporting it?

I am using react-router-redux in combination with the alpha of 3.0.0 since a long time in my app without any major issues. The only thing I recognized is that with history 3 the initial @@router/LOCATION_CHANGE  event does not get fired.
