### ISSUE TITLE
Skip very first @@router/LOCATION_CHANGE

### ISSUE THREAD

**Issue by rybon** [reactjs/react-router-redux#439]
When starting the app, this dispatch is always fired:
```
{
    "type": "@@router/LOCATION_CHANGE",
    "payload": {
        "pathname": "/",
        "search": "",
        "hash": "",
        "state": null,
        "action": "POP",
        "key": null,
        "query": {},
        "$searchBase": {
            "search": "",
            "searchBase": ""
        }
    }
}
```

Is there a way to turn that off? I tried `adjustUrlOnReplay: false`, but I still see this dispatch happening. In a test environment I want the app to be inert, in other words not trigger a dispatch on its own, so I can feed it recorded dispatches later on. Is that possible?

**Comment by dlmr** [comment]
I believe this is related to https://github.com/reactjs/react-router-redux/pull/412.

I know what is causing it and actually have what I believe is a correct fix for it locally but I have not yet had time to write good enough tests for it. Maybe I should push it as a PR so others can contribute and maybe help with the test aspects.

**Comment by slowsay** [comment]
you should be disposed combineReducers({function,function})

**Comment by rybon** [comment]
@dlmr feel free to publish your PR.

**Comment by dlmr** [comment]
@rybon I have pushed my PR as #445 but I think I misspoke unfortunately. 

It is correct that a `LOCATION_CHANGE` is dispatched on initial render. The reason for this is because there currently is no other way for the store to be initialised with the correct information, that is the correct representation of the what the browser URL is and this will be different each time since `history` is using a random `key` to make the location unique.

**Comment by chrisabrams** [comment]
I wish this fired for me on page load. I have to make a page change before seeing this.

**Comment by dlmr** [comment]
@chrisabrams If you are using SSR the change in #445 will "fix" that.

**Comment by chrisabrams** [comment]
@dlmr got it; will look forward to the "fix"

**Comment by pipi32167** [comment]
Still have the same problem, not using SSR.
