### ISSUE TITLE
URL -> state syncing without react-router

### ISSUE THREAD

**Issue by btomashvili** [reactjs/react-router-redux#440]
I am trying to sync browser history with redux. I came across with react-router-redux. But all examples what i saw is using react-router . I just want to listen any prop changes in react and drop this props in url with history.push(). However i want URL -> state syncing. Is there any simple & nice solution how to make it without react-router ?

**Comment by btomashvili** [comment]
Can i use createHistory from 'history' not from 'react-router' ? 

`import { createHistory } from 'history';`

**Comment by timdorr** [comment]
I'm not sure what you're asking. This library works on `history`, not on `react-router` directly. Your example code will work just fine (probably with another context provider for history separate from the react-redux one).

**Comment by pcompassion** [comment]
The front page of this git repository says this library bridges `react-router` and `redux`.  

And as btomashvili said, all examples are about `react-router`.   

You say this library doesn't depend on `react-router`   
I would like an example how one can use this library without `react-router`  

Because I don't need url - ui sync, I just need url data. and I think this library provides that.
