### ISSUE TITLE
Location in Redux store not honored with 4.0.6

### ISSUE THREAD

**Issue by REEMERGEMEDIA** [reactjs/react-router-redux#462]
I have an Electron app and now, with 4.0.6, the location change that is fired upon launch of the app has the pathname set as root ("/") instead of what the value currently is in the Redux store. This introduces unwanted behavior with the app now being unable to recall it's prior state. Rolling back to 4.0.5 fixes this issue. I can provide more detail as needed #445

**Comment by timdorr** [comment]
Since you're using a memory history, make sure you initialize it with the correct path (e.g., `createMemoryHistory('/foo')`. [I brought this up on the history repo](https://github.com/mjackson/history/issues/231), but it's not going to be fixed in the 2.x version. That's where the initial path comes from.
