### ISSUE TITLE
history.listen is not called after app has started

### ISSUE THREAD

**Issue by zdila** [reactjs/react-router-redux#531]
After upgrading from 4.0.7 to 4.0.8 `history.listen` is not called on app start (page load) anymore.

**Comment by timdorr** [comment]
This is how history 3.x works. You need to use `getCurrentLocation` instead.

**Comment by zdila** [comment]
No problem, but why this happened on micro version upgrade?

**Comment by timdorr** [comment]
Because it was a bug that it emulated the history 2.x behavior. It shouldn't have done that. It was causing issues with React Router hooks.

**Comment by modosc** [comment]
this is a pretty big deal though for a patch release especially since nothing in the docs mentions it:

https://github.com/reactjs/react-router-redux#how-do-i-watch-for-navigation-events-such-as-for-analytics

the release notes don't mention it. 

nor do any of the example repos you link to do this (see [here](https://github.com/davezuko/react-redux-starter-kit/blob/c2da663b52f0067027ffa7e1868f07da437a6053/src/store/createStore.js#L41) for instance)

and people using the boilerplate from [redial](https://github.com/markdalgleish/redial#example-client-usage) will also be hit by this (that's how i found the error in our codebase). 

i totally get that it was supporting a broken behavior, but maybe at least making this a minor release (if not a major one) and mentioning this change in the docs would make life easier for others who will inevitably refile this issue?

thanks!

**Comment by timdorr** [comment]
The change is upstream with going from history 2 -> 3. We're not responsible for changing it, we just had hidden that it occurred. It would be like blaming React for the same thing.

**Comment by modosc** [comment]
i understand that and i'm not blaming you for the underlying issue. i'm just pointing out that when you stopped hiding the bug (correctly or not) it had the potential to break lots of code, and by doing that in a patch release it introduced a subtle bug that i spent the morning tracking down. at least adding something to the `README.md` mentioning this would be awesome and i'd be happy to write it up that makes life easier, i doubt i'm the only one who was hit by this.
